"""empty message

Revision ID: 2380846c867a
Revises: af534bdc54a4
Create Date: 2020-08-21 11:49:15.701268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2380846c867a'
down_revision = 'af534bdc54a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multisport', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'multisport', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multisport', type_='foreignkey')
    op.drop_column('multisport', 'user_id')
    # ### end Alembic commands ###
