"""empty message

Revision ID: af534bdc54a4
Revises: 
Create Date: 2020-08-04 13:24:56.710986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af534bdc54a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multisport', sa.Column('classes_rate', sa.Integer(), nullable=True))
    op.add_column('multisport', sa.Column('training_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multisport', 'training_rate')
    op.drop_column('multisport', 'classes_rate')
    # ### end Alembic commands ###
